/* Q1. How many customers are there? */

/* Q2. How many customers have churned? */

/* Q3. What is the overall churn rate (%)? */

/* Q4. What is the gender distribution of customers? */

/* Q5. How many customers are senior citizens? */

/* Q6. What percentage of customers are senior citizens? */

/* Q7. How many customers have partners? */

/* Q8. How many customers have dependents? */

/* Q9. What is the average customer tenure? */

/* Q10. What is the average tenure of churned customers? */

/* Q11. What is the average tenure of retained customers? */

/* Q12. What is the minimum and maximum tenure? */

/* =========================
   CUSTOMER DEMOGRAPHICS
   ========================= */

/* Q13. Does gender affect churn? */

/* Q14. Are senior citizens more likely to churn? */

/* Q15. Do customers with partners churn less? */

/* Q16. Do customers with dependents churn less? */

/* Q17. Churn rate by gender */

/* Q18. Churn rate by senior citizen status */

/* Q19. Churn rate by partner status */

/* Q20. Churn rate by dependent status */

/* =========================
   SERVICE ANALYSIS
   ========================= */

/* Q21. Which phone service option is most used? */

/* Q22. Does having multiple lines affect churn? */

/* Q23. Which internet service type is most popular? */

/* Q24. Which internet service type has the highest churn? */

/* Q25. Does online security reduce churn? */

/* Q26. Does online backup reduce churn? */

/* Q27. Does device protection reduce churn? */

/* Q28. Does tech support reduce churn? */

/* Q29. Does streaming TV affect churn? */

/* Q30. Does streaming movies affect churn? */

/* Q31. Compare churn rates across all internet-related services. */

/* =========================
   CONTRACT ANALYSIS
   ========================= */

/* Q32. Which contract type is most common? */

/* Q33. Which contract type has the highest churn? */

/* Q34. Churn rate by contract type. */

/* Q35. Average tenure by contract type. */

/* Q36. Revenue generated by each contract type. */

/* Q37. Which contract type retains customers the longest? */

/* =========================
   PAYMENT ANALYSIS
   ========================= */

/* Q38. Which payment method is used most frequently? */

/* Q39. Which payment method has the highest churn? */

/* Q40. Churn rate by payment method. */

/* Q41. Does paperless billing affect churn? */

/* Q42. Churn rate by paperless billing status. */

/* =========================
   REVENUE ANALYSIS
   ========================= */

/* Q43. What is the total revenue generated? */

/* Q44. What is the average monthly charge? */

/* Q45. What is the average total charge? */

/* Q46. Average monthly charges of churned customers. */

/* Q47. Average monthly charges of retained customers. */

/* Q48. Average total charges of churned customers. */

/* Q49. Average total charges of retained customers. */

/* Q50. Are high-paying customers more likely to churn? */

/* Q51. Top 10 highest-paying customers. */

/* Q52. Top 10 customers with longest tenure. */

/* =========================
   CUSTOMER SEGMENTATION
   ========================= */

/* Q53. Segment customers by tenure (New, Regular, Loyal). */

/* Q54. Which customer segment has the highest churn? */

/* Q55. Revenue contribution by customer segment. */

/* Q56. Average monthly charges by customer segment. */

/* Q57. Average tenure by customer segment. */

/* =========================
   ADVANCED BUSINESS QUESTIONS
   ========================= */

/* Q58. Top 5 churn-driving factors based on churn rates. */

/* Q59. Which combination of contract and payment method has the highest churn? */

/* Q60. Which internet service + contract combination has the highest churn? */

/* Q61. Which customer group generates the most revenue? */

/* Q62. Which customer group is most at risk of churning? */

/* Q63. Identify customers with high monthly charges and low tenure. */

/* Q64. Identify loyal customers with tenure above 60 months. */

/* Q65. Identify customers likely to churn based on historical patterns. */

/* Q66. Compare churn rates between customers with and without tech support. */

/* Q67. Compare churn rates between customers with and without online security. */

/* Q68. Compare churn rates between customers with and without device protection. */

/* Q69. Compare churn rates between customers with and without streaming services. */

/* Q70. What customer retention recommendations can be derived from the analysis? */